---
abstract: "Interface to mercurial's command server"
author:
  - 'Diab Jerius E<lt>djerius@cpan.orgE<gt>'
build_requires:
  Getopt::Long: 0
  IO::Handle: 0
  IO::Pipe: 0
  Moo::Role: 0
  Probe::Perl: 0
  Sub::Quote: 0
  Test::Exception: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.40
dynamic_config: 1
generated_by: 'Module::Build version 0.4004, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Hg-Lib
provides:
  Hg::Lib:
    file: lib/Hg/Lib.pm
    version: 0.01_04
  Hg::Lib::Server:
    file: lib/Hg/Lib/Server.pm
requires:
  Moo: 1.001000
  MooX::Attributes::Shadow: 0
  MooX::Types::MooseLike: 0
  Params::Validate: 0
  Scalar::Util: 0
  System::Command: 0
  Try::Tiny: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: https://bitbucket.org/djerius/hg-lib
version: 0.01_04
