---
abstract: "interface to mercurial's command server"
author:
  - 'Diab Jerius <djerius@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Moo::Role: 0
  Probe::Perl: 0
  Test::Exception: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Hg-Lib
no_index:
  directory:
    - inc
    - t
requires:
  Moo: 0
  MooX::Attributes::Shadow: 0
  MooX::Types::MooseLike: 0
  Try::Tiny: 0
  perl: 5.10.1
resources:
  license: http://dev.perl.org/licenses/
  repository: https://bitbucket.org/djerius/hg-lib
version: 0.01_01
