---
abstract: "interface to mercurial's command server"
author:
  - 'Diab Jerius E<lt>djerius@cpan.orgE<gt>'
build_requires:
  Capture::Tiny: 0
  File::Spec::Functions: 0
  File::Which: 0
  File::pushd: 0
  Getopt::Long: 0
  IO::Handle: 0
  Moo: 1.003000
  Moo::Role: 1.003000
  Probe::Perl: 0
  Safe::Isa: 0
  Sub::Quote: 0
  Test::Class: 0
  Test::Directory: 0
  Test::Fatal: 0
  Test::File: 0
  Test::Lib: 0
  Test::More: 0
  Test::Roo: 0
  Test::Roo::Role: 0
  Type::Params: 0
  YAML::Tiny: 0
  boolean: 0
configure_requires:
  File::Which: 0
  Module::Build: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.4004, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Hg-Lib
provides:
  Hg::Lib:
    file: lib/Hg/Lib.pm
    version: 0.01_05
  Hg::Lib::Client:
    file: lib/Hg/Lib/Client.pm
  Hg::Lib::Client::Result:
    file: lib/Hg/Lib/Client/Result.pm
  Hg::Lib::Exception:
    file: lib/Hg/Lib/Exception.pm
  Hg::Lib::Exception::Command:
    file: lib/Hg/Lib/Exception.pm
  Hg::Lib::Server:
    file: lib/Hg/Lib/Server.pm
  Hg::Lib::Server::Pipe:
    file: lib/Hg/Lib/Server/Pipe.pm
  Hg::Lib::Types:
    file: lib/Hg/Lib/Types.pm
  Hg::Lib::Utils:
    file: lib/Hg/Lib/Utils.pm
requires:
  Capture::Tiny: 0
  Exporter: 0
  Exporter::Tiny: 0
  File::Which: 0
  FileHandle: 0
  IO::Select: 0
  Moo: 1.003000
  MooX::Attributes::Shadow: 0.03
  System::Command: 0
  Throwable: 0
  Try::Tiny: 0
  Type::Library: 0.028
  Type::Params: 0.028
  Type::Tiny: 0.028
  Type::Utils: 0.028
  Types::Standard: 0.028
  autodie: 0
  boolean: 0
  feature: 0
  perl: v5.10.1
resources:
  license: http://dev.perl.org/licenses/
  repository: https://bitbucket.org/djerius/hg-lib
version: 0.01_05
